import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

// Load Custom Fonts
const geistSans = localFont({
  src: "/fonts/GeistVF.woff", // Ensure fonts are in the public directory
  variable: "--font-geist-sans",
  weight: "100 900",
  style: "normal",
  display: "swap", // Improve font rendering performance
});

const geistMono = localFont({
  src: "/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
  style: "normal",
  display: "swap",
});

// Metadata for SEO
export const metadata = {
  title: "E-commerce site",
  description: "Generated by create next app",
  lang: "en", // Use dynamic lang if needed
};

export default function RootLayout({ children }) {
  return (
    <html lang={metadata.lang}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <main className="container mx-auto px-4">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
